FIELD_CHOICES = [
    ("DomainName", "Domain Name"),
    ("NameServers", "Name Server"),
    ("WhoisServer", "Whois Server"),
    ("Status", "Status"),
    ("RegistrarName", "Registrar Name"),
    ("Email", "Email"),
    ("RegistrantContact.Name", "Registrant Contact: Name"),
    ("RegistrantContact.Organization", "Registrant Contact: Organization"),
    ("RegistrantContact.Email", "Registrant Contact: Email"),
    ("RegistrantContact.City", "Registrant Contact: City"),
    ("RegistrantContact.Country", "Registrant Contact: Country"),
    ("RegistrantContact.PostalCode", "Registrant Contact: Postal Code"),
    ("RegistrantContact.State", "Registrant Contact: State"),
    ("RegistrantContact.StreetAddress", "Registrant Contact: Street Address"),
    ("RegistrantContact.Telephone", "Registrant Contact: Telephone"),
    (
        "RegistrantContact.TelephoneExtension",
        "Registrant Contact: Telephone Extension",
    ),
    ("RegistrantContact.Fax", "Registrant Contact: Fax"),
    ("RegistrantContact.FaxExtension", "Registrant Contact: Fax Extension"),
    ("AdminContact.Name", "Admin Contact: Name"),
    ("AdminContact.Organization", "Admin Contact: Organization"),
    ("AdminContact.Email", "Admin Contact: Email"),
    ("AdminContact.City", "Admin Contact: City"),
    ("AdminContact.Country", "Admin Contact: Country"),
    ("AdminContact.PostalCode", "Admin Contact: Postal Code"),
    ("AdminContact.State", "Admin Contact: State"),
    ("AdminContact.StreetAddress", "Admin Contact: Street Address"),
    ("AdminContact.Telephone", "Admin Contact: Telephone"),
    (
        "AdminContact.TelephoneExtension",
        "Admin Contact: Telephone Extension",
    ),
    ("AdminContact.Fax", "Admin Contact: Fax"),
    ("AdminContact.FaxExtension", "Admin Contact: Fax Extension"),
    ("BillingContact.Name", "Billing Contact: Name"),
    ("BillingContact.Organization", "Billing Contact: Organization"),
    ("BillingContact.Email", "Billing Contact: Email"),
    ("BillingContact.City", "Billing Contact: City"),
    ("BillingContact.Country", "Billing Contact: Country"),
    ("BillingContact.PostalCode", "Billing Contact: Postal Code"),
    ("BillingContact.State", "Billing Contact: State"),
    ("BillingContact.StreetAddress", "Billing Contact: Street Address"),
    ("BillingContact.Telephone", "Billing Contact: Telephone"),
    (
        "BillingContact.TelephoneExtension",
        "Billing Contact: Telephone Extension",
    ),
    ("BillingContact.Fax", "Billing Contact: Fax"),
    ("BillingContact.FaxExtension", "Billing Contact: Fax Extension"),
    ("TechContact.Name", "Tech Contact: Name"),
    ("TechContact.Organization", "Tech Contact: Organization"),
    ("TechContact.Email", "Tech Contact: Email"),
    ("TechContact.City", "Tech Contact: City"),
    ("TechContact.Country", "Tech Contact: Country"),
    ("TechContact.PostalCode", "Tech Contact: Postal Code"),
    ("TechContact.State", "Tech Contact: State"),
    ("TechContact.StreetAddress", "Tech Contact: Street Address"),
    ("TechContact.Telephone", "Tech Contact: Telephone"),
    (
        "TechContact.TelephoneExtension",
        "Tech Contact: Telephone Extension",
    ),
    ("TechContact.Fax", "Tech Contact: Fax"),
    ("TechContact.FaxExtension", "Tech Contact: Fax Extension"),
]
