# Generated by Django 6.0.2 on 2026-03-06 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('source_kind', models.CharField(choices=[('text', 'Text'), ('url', 'URL'), ('file', 'File')], max_length=16)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('fetched_url', models.URLField(blank=True, max_length=2000)),
                ('primary_source_url', models.URLField(blank=True, max_length=2000)),
                ('used_source_url', models.URLField(blank=True, max_length=2000)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('source_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['source_kind', 'created'], name='report_inte_source__b205d1_idx'), models.Index(fields=['used_source_url'], name='report_inte_used_so_9396d2_idx'), models.Index(fields=['primary_source_url'], name='report_inte_primary_0c15da_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreatReportAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('extractor_version', models.CharField(default='v1', max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=255)),
                ('model_enrichment_used', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('raw_result', models.JSONField(blank=True, default=dict)),
                ('validation_warnings', models.JSONField(blank=True, default=list)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='report_intelligence.threatreport')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatReportDetectionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rule_type', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_rules', to='report_intelligence.threatreportanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatReportEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('entity_type', models.CharField(choices=[('victim_organization', 'Victim Organization'), ('reporting_organization', 'Reporting Organization'), ('vendor_organization', 'Vendor Organization'), ('victim_industry', 'Victim Industry'), ('victim_geography', 'Victim Geography'), ('threat_actor', 'Threat Actor'), ('associated_threat_actor', 'Associated Threat Actor'), ('malware', 'Malware'), ('associated_malware', 'Associated Malware'), ('campaign', 'Campaign')], max_length=64)),
                ('name', models.CharField(max_length=500)),
                ('role', models.CharField(blank=True, max_length=64)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='report_intelligence.threatreportanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatReportIOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField()),
                ('ioc_type', models.CharField(choices=[('url', 'URL'), ('domain', 'Domain'), ('ipv4', 'IPv4'), ('ipv6', 'IPv6'), ('hash', 'Hash'), ('email', 'Email'), ('cve', 'CVE'), ('asn', 'ASN')], max_length=32)),
                ('disposition', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('legitimate_tool', 'Legitimate Tool'), ('detected', 'Detected')], max_length=32)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source_section', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('context_snippet', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iocs', to='report_intelligence.threatreportanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatReportRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source_name', models.CharField(max_length=500)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('relationship', models.CharField(max_length=64)),
                ('target_name', models.CharField(max_length=500)),
                ('target_type', models.CharField(blank=True, max_length=64)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='report_intelligence.threatreportanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatReportTTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('ttp', 'TTP'), ('emerging_technique', 'Emerging Technique'), ('emerging_procedure', 'Emerging Procedure')], default='ttp', max_length=32)),
                ('description', models.TextField()),
                ('tactics', models.JSONField(blank=True, default=list)),
                ('techniques', models.JSONField(blank=True, default=list)),
                ('procedures', models.JSONField(blank=True, default=list)),
                ('why_new', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ttps', to='report_intelligence.threatreportanalysis')),
            ],
        ),
        migrations.AddIndex(
            model_name='threatreportanalysis',
            index=models.Index(fields=['created'], name='report_inte_created_44f26b_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportanalysis',
            index=models.Index(fields=['model_enrichment_used'], name='report_inte_model_e_187d22_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportdetectionrule',
            index=models.Index(fields=['rule_type'], name='report_inte_rule_ty_be40ae_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportdetectionrule',
            index=models.Index(fields=['analysis', 'rule_type'], name='report_inte_analysi_4928b8_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportentity',
            index=models.Index(fields=['entity_type', 'name'], name='report_inte_entity__b9896f_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportentity',
            index=models.Index(fields=['analysis', 'entity_type'], name='report_inte_analysi_c6bf92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threatreportentity',
            unique_together={('analysis', 'entity_type', 'name', 'role')},
        ),
        migrations.AddIndex(
            model_name='threatreportioc',
            index=models.Index(fields=['ioc_type', 'disposition'], name='report_inte_ioc_typ_62a9a3_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportioc',
            index=models.Index(fields=['analysis', 'disposition'], name='report_inte_analysi_01f3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportrelationship',
            index=models.Index(fields=['relationship'], name='report_inte_relatio_54a400_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportrelationship',
            index=models.Index(fields=['source_name'], name='report_inte_source__b1eac5_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportrelationship',
            index=models.Index(fields=['target_name'], name='report_inte_target__7edacb_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportttp',
            index=models.Index(fields=['kind'], name='report_inte_kind_94dd48_idx'),
        ),
        migrations.AddIndex(
            model_name='threatreportttp',
            index=models.Index(fields=['analysis', 'kind'], name='report_inte_analysi_86ac47_idx'),
        ),
    ]
