# Generated by Django 6.0.2 on 2026-03-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatreportdetectionrule',
            name='confidence_label',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='threatreportdetectionrule',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='threatreportentity',
            name='confidence_label',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='threatreportentity',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='threatreportrelationship',
            name='confidence_label',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='threatreportrelationship',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='threatreportttp',
            name='confidence_label',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='threatreportttp',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='threatreportioc',
            constraint=models.UniqueConstraint(fields=('analysis', 'value', 'ioc_type', 'disposition', 'source_section', 'source_url'), name='uniq_analysis_ioc_value_scope'),
        ),
        migrations.AddConstraint(
            model_name='threatreportrelationship',
            constraint=models.UniqueConstraint(fields=('analysis', 'source_name', 'relationship', 'target_name', 'source_type', 'target_type'), name='uniq_analysis_relationship'),
        ),
        migrations.AddConstraint(
            model_name='threatreportttp',
            constraint=models.UniqueConstraint(fields=('analysis', 'kind', 'description'), name='uniq_analysis_ttp_kind_description'),
        ),
    ]
