# Generated by Django 6.0.2 on 2026-03-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_intelligence', '0003_threatreportanalysis_snapshot_and_ioc_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatreportentity',
            name='entity_type',
            field=models.CharField(choices=[('victim_organization', 'Victim Organization'), ('reporting_organization', 'Reporting Organization'), ('vendor_organization', 'Vendor Organization'), ('victim_industry', 'Victim Industry'), ('victim_geography', 'Victim Geography'), ('threat_actor', 'Threat Actor'), ('malware', 'Malware'), ('campaign', 'Campaign')], max_length=64),
        ),
    ]
