# Generated by Django 6.0.2 on 2026-03-07 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_intelligence', '0004_alter_threatreportentity_entity_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='threatreportrelationship',
            name='uniq_analysis_relationship',
        ),
        migrations.AddField(
            model_name='threatreportrelationship',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='report_intelligence.threatreportrelationship'),
        ),
        migrations.AddIndex(
            model_name='threatreportrelationship',
            index=models.Index(fields=['parent'], name='report_inte_parent__97f864_idx'),
        ),
        migrations.AddConstraint(
            model_name='threatreportrelationship',
            constraint=models.UniqueConstraint(fields=('analysis', 'parent', 'source_name', 'relationship', 'target_name', 'source_type', 'target_type'), name='uniq_analysis_relationship'),
        ),
    ]
