# Generated by Django 6.0.2 on 2026-03-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_intelligence', '0006_refactor_ttp_emerging_flags'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='threatreportttp',
            new_name='report_inte_is_emer_468877_idx',
            old_name='report_inte_is_eme_4f4515_idx',
        ),
        migrations.RenameIndex(
            model_name='threatreportttp',
            new_name='report_inte_analysi_b8ca12_idx',
            old_name='report_inte_analysi_c25b32_idx',
        ),
    ]
