# Generated by Django 6.0.2 on 2026-03-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_intelligence', '0007_rename_report_inte_is_eme_4f4515_idx_report_inte_is_emer_468877_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatreportentity',
            name='entity_type',
            field=models.CharField(choices=[('victim_organization', 'Victim Organization'), ('victim_industry', 'Victim Industry'), ('victim_geography', 'Victim Geography'), ('threat_actor', 'Threat Actor'), ('malware', 'Malware'), ('campaign', 'Campaign')], max_length=64),
        ),
    ]
