# Generated by Django 6.0.2 on 2026-02-22 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewlyRegisteredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'indexes': [models.Index(fields=['status'], name='domain_moni_status_af75aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='LookalikeDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('watched_resource', models.CharField(max_length=255)),
                ('potential_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('takedown', 'Takedown Requested'), ('legal', 'Sent to Legal'), ('not_relevant', 'Not Relevant')], default='open', max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookalike_domains', to='domain_monitoring.company')),
            ],
            options={
                'verbose_name_plural': 'Lookalike Domains',
            },
        ),
        migrations.CreateModel(
            name='LookalikeDomainComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('lookalike_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='domain_monitoring.lookalikedomain')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('a_record', models.JSONField(blank=True, default=list)),
                ('mx_record', models.JSONField(blank=True, default=list)),
                ('subdomains', models.JSONField(blank=True, default=list)),
                ('spf_record', models.TextField(blank=True, max_length=1000)),
                ('website_url', models.URLField(blank=True, max_length=1000)),
                ('website_status_code', models.CharField(blank=True, max_length=3)),
                ('website_screenshot', models.CharField(blank=True, max_length=500)),
                ('website_certificate', models.JSONField(blank=True, default=list)),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_domains', to='domain_monitoring.company')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredDomainAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('a_record', models.JSONField(blank=True, default=list)),
                ('mx_record', models.JSONField(blank=True, default=list)),
                ('spf_record', models.TextField(blank=True, max_length=1000)),
                ('subdomains', models.JSONField(blank=True, default=list)),
                ('website_url', models.URLField(blank=True, max_length=1000)),
                ('website_status_code', models.CharField(blank=True, max_length=3)),
                ('website_screenshot', models.CharField(blank=True, max_length=500)),
                ('website_certificate', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_domain_alerts', to='domain_monitoring.company')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredDomainAlertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='domain_monitoring.monitoreddomainalert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('cert_index', models.IntegerField()),
                ('cert_domain', models.CharField(max_length=255)),
                ('watched_domain', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificates', to='domain_monitoring.company')),
            ],
        ),
        migrations.CreateModel(
            name='WatchedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('keyword', 'Keyword'), ('domain', 'Domain')], max_length=10)),
                ('properties', models.JSONField(blank=True, default=list)),
                ('exclude_keywords', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_resources', to='domain_monitoring.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_domains', to='domain_monitoring.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'status'], name='domain_moni_company_5a6bce_idx'), models.Index(fields=['value'], name='domain_moni_value_bd509d_idx')],
                'unique_together': {('value', 'company')},
            },
        ),
        migrations.AddIndex(
            model_name='lookalikedomain',
            index=models.Index(fields=['company', 'status'], name='domain_moni_company_4bf338_idx'),
        ),
        migrations.AddIndex(
            model_name='lookalikedomain',
            index=models.Index(fields=['source_date'], name='domain_moni_source__349184_idx'),
        ),
        migrations.AddIndex(
            model_name='lookalikedomain',
            index=models.Index(fields=['potential_risk', 'status'], name='domain_moni_potenti_d8694c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lookalikedomain',
            unique_together={('source_date', 'value', 'company')},
        ),
        migrations.AddIndex(
            model_name='monitoreddomain',
            index=models.Index(fields=['company', 'status'], name='domain_moni_company_b65558_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoreddomain',
            index=models.Index(fields=['last_checked'], name='domain_moni_last_ch_43022a_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoreddomain',
            index=models.Index(fields=['value'], name='domain_moni_value_4591ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoreddomain',
            unique_together={('value', 'company')},
        ),
        migrations.AddIndex(
            model_name='monitoreddomainalert',
            index=models.Index(fields=['company', 'status'], name='domain_moni_company_5bbb03_idx'),
        ),
        migrations.AddIndex(
            model_name='monitoreddomainalert',
            index=models.Index(fields=['domain_name'], name='domain_moni_domain__bc6731_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monitoreddomainalert',
            unique_together={('domain_name', 'company')},
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['company', 'watched_domain'], name='domain_moni_company_580456_idx'),
        ),
        migrations.AddIndex(
            model_name='sslcertificate',
            index=models.Index(fields=['cert_domain'], name='domain_moni_cert_do_716b54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sslcertificate',
            unique_together={('cert_index', 'cert_domain', 'watched_domain', 'company')},
        ),
        migrations.AddIndex(
            model_name='watchedresource',
            index=models.Index(fields=['company', 'status'], name='domain_moni_company_23da06_idx'),
        ),
        migrations.AddIndex(
            model_name='watchedresource',
            index=models.Index(fields=['resource_type'], name='domain_moni_resourc_adb104_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchedresource',
            unique_together={('value', 'company')},
        ),
    ]
