# Generated by Django 6.0.2 on 2026-02-05 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='NewlyRegisteredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LookalikeDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('watched_resource', models.CharField(max_length=255)),
                ('potential_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('takedown', 'Takedown Requested'), ('legal', 'Sent to Legal'), ('not_relevant', 'Not Relevant')], default='open', max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_monitoring.company')),
            ],
            options={
                'verbose_name_plural': 'Lookalike Domains',
                'unique_together': {('source_date', 'value', 'company')},
            },
        ),
        migrations.CreateModel(
            name='LookalikeDomainComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('lookalike_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='domain_monitoring.lookalikedomain')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoredDomainAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255)),
                ('a_record', models.JSONField(blank=True, default=list)),
                ('mx_record', models.JSONField(blank=True, default=list)),
                ('spf_record', models.TextField(blank=True, max_length=1000)),
                ('subdomains', models.JSONField(blank=True, default=list)),
                ('website_url', models.URLField(blank=True, max_length=1000)),
                ('website_status_code', models.CharField(blank=True, max_length=3)),
                ('website_screenshot', models.TextField(blank=True, max_length=1000)),
                ('website_certificate', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_monitoring.company')),
            ],
            options={
                'unique_together': {('domain_name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='MonitoredDomainAlertComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='domain_monitoring.monitoreddomainalert')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_monitoring.company')),
            ],
            options={
                'unique_together': {('value', 'company')},
            },
        ),
        migrations.CreateModel(
            name='MonitoredDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('a_record', models.JSONField(blank=True, default=list)),
                ('mx_record', models.JSONField(blank=True, default=list)),
                ('subdomains', models.JSONField(blank=True, default=list)),
                ('spf_record', models.TextField(blank=True, max_length=1000)),
                ('website_url', models.URLField(blank=True, max_length=1000)),
                ('website_status_code', models.CharField(blank=True, max_length=3)),
                ('website_screenshot', models.CharField(blank=True, max_length=255)),
                ('website_certificate', models.JSONField(blank=True, default=list)),
                ('last_checked', models.DateField(default='1900-01-01')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_monitoring.company')),
            ],
            options={
                'unique_together': {('value', 'company')},
            },
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True)),
                ('cert_index', models.IntegerField()),
                ('cert_domain', models.CharField(max_length=255)),
                ('watched_domain', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_monitoring.company')),
            ],
            options={
                'unique_together': {('cert_index', 'cert_domain', 'watched_domain', 'company')},
            },
        ),
        migrations.CreateModel(
            name='WatchedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('keyword', 'Keyword'), ('domain', 'Domain')], max_length=255)),
                ('properties', models.JSONField(blank=True, default=list)),
                ('exclude_keywords', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_monitoring.company')),
            ],
            options={
                'unique_together': {('value', 'company')},
            },
        ),
    ]
