# Generated by Django 5.0.7 on 2024-08-04 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_monitoring', '0002_lookalikedomain_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookalikedomain',
            name='potential_risk',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('unknown', 'Unknown')], default='unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='lookalikedomain',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('takedown', 'Takedown Requested'), ('legal', 'Sent to Legal'), ('not_relevant', 'Not Relevant')], default='open', max_length=12),
        ),
    ]
