# Generated by Django 6.0.2 on 2026-02-14 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_monitoring', '0003_schema_improvements'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='domain_moni_status_af75aa_idx',
            old_name='dm_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='companydomain',
            new_name='domain_moni_company_5a6bce_idx',
            old_name='dm_companydomain_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='companydomain',
            new_name='domain_moni_value_bd509d_idx',
            old_name='dm_companydomain_value_idx',
        ),
        migrations.RenameIndex(
            model_name='lookalikedomain',
            new_name='domain_moni_company_4bf338_idx',
            old_name='dm_lookalikedomain_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='lookalikedomain',
            new_name='domain_moni_source__349184_idx',
            old_name='dm_lookalikedomain_source_date_idx',
        ),
        migrations.RenameIndex(
            model_name='lookalikedomain',
            new_name='domain_moni_potenti_d8694c_idx',
            old_name='dm_lookalikedomain_risk_status_idx',
        ),
        migrations.RenameIndex(
            model_name='monitoreddomain',
            new_name='domain_moni_company_b65558_idx',
            old_name='dm_monitoreddomain_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='monitoreddomain',
            new_name='domain_moni_last_ch_43022a_idx',
            old_name='dm_monitoreddomain_last_checked_idx',
        ),
        migrations.RenameIndex(
            model_name='monitoreddomain',
            new_name='domain_moni_value_4591ee_idx',
            old_name='dm_monitoreddomain_value_idx',
        ),
        migrations.RenameIndex(
            model_name='monitoreddomainalert',
            new_name='domain_moni_company_5bbb03_idx',
            old_name='dm_monitoreddomainalert_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='monitoreddomainalert',
            new_name='domain_moni_domain__bc6731_idx',
            old_name='dm_monitoreddomainalert_domain_name_idx',
        ),
        migrations.RenameIndex(
            model_name='sslcertificate',
            new_name='domain_moni_company_580456_idx',
            old_name='dm_sslcertificate_company_watched_idx',
        ),
        migrations.RenameIndex(
            model_name='sslcertificate',
            new_name='domain_moni_cert_do_716b54_idx',
            old_name='dm_sslcertificate_cert_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='watchedresource',
            new_name='domain_moni_company_23da06_idx',
            old_name='dm_watchedresource_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='watchedresource',
            new_name='domain_moni_resourc_adb104_idx',
            old_name='dm_watchedresource_type_idx',
        ),
        migrations.AlterField(
            model_name='companydomain',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_domains', to='domain_monitoring.company'),
        ),
        migrations.AlterField(
            model_name='lookalikedomain',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookalike_domains', to='domain_monitoring.company'),
        ),
        migrations.AlterField(
            model_name='monitoreddomain',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_domains', to='domain_monitoring.company'),
        ),
        migrations.AlterField(
            model_name='monitoreddomainalert',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_domain_alerts', to='domain_monitoring.company'),
        ),
        migrations.AlterField(
            model_name='sslcertificate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificates', to='domain_monitoring.company'),
        ),
        migrations.AlterField(
            model_name='watchedresource',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_resources', to='domain_monitoring.company'),
        ),
    ]
