# Generated by Django 6.0.2 on 2026-03-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_monitoring', '0004_domainmonitoringsettings'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monitoreddomainscreenshotpattern',
            new_name='domain_moni_monitor_9271e9_idx',
            old_name='domain_moni_monitor_9b9759_idx',
        ),
        migrations.RenameIndex(
            model_name='monitoreddomainscreenshotpattern',
            new_name='domain_moni_pattern_2f3a39_idx',
            old_name='domain_moni_pattern_bf55f2_idx',
        ),
    ]
