# Generated by Django 6.0.2 on 2026-02-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.TextField(max_length=1000)),
                ('value_type', models.CharField(choices=[('domain', 'Domain'), ('url', 'URL'), ('ipv4', 'IPv4'), ('ipv6', 'IPv6'), ('md5', 'MD5'), ('sha1', 'SHA1'), ('sha256', 'SHA256'), ('email', 'Email Address'), ('cve', 'CVE')], max_length=255)),
                ('hashed_value', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('data', models.TextField(max_length=10000)),
            ],
            options={
                'unique_together': {('hashed_value', 'source')},
            },
        ),
    ]
