# Generated by Django 6.0.2 on 2026-02-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence_harvester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='data',
            field=models.JSONField(),
        ),
    ]
