# Generated by Django 6.0.2 on 2026-02-22 19:45

from django.db import migrations
import json


def convert_json_strings_to_objects(apps, schema_editor):
    """
    Convert existing TextField JSON strings to actual JSON objects.
    This handles the migration from TextField to JSONField.
    """
    Source = apps.get_model('intelligence_harvester', 'Source')
    
    for source in Source.objects.all():
        # If data is a string (from old TextField), parse it to JSON
        if isinstance(source.data, str):
            try:
                source.data = json.loads(source.data)
                source.save(update_fields=['data'])
            except json.JSONDecodeError:
                # If parsing fails, skip this record (or handle as needed)
                print(f"Warning: Could not parse JSON for Source id={source.id}")
                pass


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: convert JSON objects back to strings.
    """
    Source = apps.get_model('intelligence_harvester', 'Source')
    
    for source in Source.objects.all():
        # If data is a dict/list (JSON), convert it to string
        if not isinstance(source.data, str):
            source.data = json.dumps(source.data)
            source.save(update_fields=['data'])


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence_harvester', '0002_convert_data_to_jsonfield'),
    ]

    operations = [
        migrations.RunPython(convert_json_strings_to_objects, reverse_migration),
    ]
